FROM apachesuperset.docker.scarf.sh/apache/superset:latest

USER root

RUN pip install --no-cache-dir \
    clickhouse-connect \
    clickhouse-sqlalchemy \
    sqlalchemy==1.4.36 \
    sqlalchemy-bigquery==1.6.1

USER superset
